modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "deep_space"
version = "${version}"
displayName = "Deep Space"
authors = "G_Mungus"
description = '''
Starlance Addon
'''
#logoFile = ""

[[dependencies.deep_space]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deep_space]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
